# Generated by Django 5.2.11 on 2026-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
